
# language
LANG_LANGUAGE_FULLNAME:
  en: english
  uy: uyghur_uay
  ug: uyghur_uly
  uz: uzbek
  tr: turkish
  kz: kazakh
LANG_LANGUAGE_TRANSLATION:
  en: english
  uy: ئۇيغۇرچە
  ug: uyghurche
  uz: o'zbekcha
  tr: Türkçe
  kz: қазақша
