// language

#define LANG_ERR "XATALIQ"
#define LANG_WAR "ESKERTME"
#define LANG_LOG "UCHUR"
#define LANG_TRACE "IZLAR"
#define LANG_UNKNOWN "NAMELUM"
#define LANG_ERR_NO_VALID_STATE "inawetsiz halet kuruldi"
#define LANG_ERR_NO_INPUT_NAME "uyghur script programma hejjet ismi birilmidi"

// uyghur
#define LANG_ERR_UYGHUR_EXCEPTION "programma xataliqi kuruldi"
#define LANG_ERR_UYGHUR_FILE_NOT_FOUND "programma hojjiti tepilmidi, adirsi:[%s]\n"
#define LANG_ERR_SOME_PLACE "hojjet:[%s], qur:[%d], qatar:[%d]"
#define LANG_ERR_SIGN_PLACE LANG_ERR_SOME_PLACE ", herip:[%c]"
#define LANG_ERR_TOKEN_PLACE LANG_ERR_SOME_PLACE ", belge:[%s]"
#define LANG_ERR_INVALID_TYPE "inawetsiz tip uchritildi"
#define LANG_ERR_INVALID_LTTR "inawetsiz xet uchritildi"
#define LANG_ERR_INVALID_WORD "inawetsiz soz uchritildi"
#define LANG_ERR_INVALID_NAME "inawetsiz nam uchritildi"
#define LANG_ERR_INVALID_NMBR "inawetsiz san uchritildi"
#define LANG_ERR_INVALID_STRG "inawetsiz xet uchritildi"
#define LANG_ERR_CANNOT_BE_FLOAT "parche san bolsa bolmaydu"

// tokenizer
#define LANG_ERR_TOKENIZER_EXCEPTION "imla xataliqi kuruldi"
#define LANG_ERR_TOKENIZER_INVALID_SIGN "uchritilghan herip inawetsiz"
#define LANG_ERR_TOKENIZER_INVALID_KEY "achquch ismi inawetsiz"
#define LANG_ERR_TOKENIZER_INVALID_BOX "sanduq ismi inawetsiz"
#define LANG_ERR_TOKENIZER_STRING_START_ERROR "xet beshi xata"
#define LANG_ERR_TOKENIZER_STRING_END_ERROR "xet axiri xata"
#define LANG_ERR_TOKENIZER_KEY_START_ERROR "achquch beshi xata"
#define LANG_ERR_TOKENIZER_KEY_END_ERROR "achquch axiri xata"

// parser
#define LANG_ERR_PARSER_EXCEPTION "logika xataliqi kuruldi"
#define LANG_ERR_PARSER_DESIRED_VALUE_NOT_FOUND "keynidin umut qilinghan qimmet tepilmidi"
#define LANG_ERR_PARSER_INVALID_IF "eger jumlisi inawetsiz"
#define LANG_ERR_PARSER_INVALID_CALCULATOR "hisablash jumlisi inawetsiz"

// executer
#define LANG_ERR_EXECUTER_EXCEPTION "ijra xataliqi kuruldi"
#define LANG_ERR_EXECUTER_NOT_IMPLEMENTED "ijra qilish qollanmidi:[%c]"
#define LANG_ERR_EXECUTER_CONTAINER_NOT_FOUND "nishanlanghan sanduq tepilmidi"
#define LANG_ERR_EXECUTER_EXP_INVALID_TYPE "oxshashmighan miqdar tipi arisida xisablash elip barghili bolmaydu"
#define LANG_ERR_EXECUTER_KEY_INVALID_TOKEN "inawetsiz achquch uchritildi"
#define LANG_ERR_EXECUTER_CALCULATION_INVALID "hisablash meshghulati inawetsiz:[%s]"
#define LANG_ERR_EXECUTER_CALCULATION_INVALID_SIGN "hisablash belgisi qollanmidi"
#define LANG_ERR_EXECUTER_CALCULATION_INVALID_ARGS "hisablash miqtarliri qollanmidi"
#define LANG_ERR_EXECUTER_CALCULATION_INVALID_STAT "hisablash heliti inawetsiz"
#define LANG_ERR_EXECUTER_INVALID_IF "eger jumlisi inawetsiz"
#define LANG_ERR_EXECUTER_BRIDGE_INVALID_RESULT "kowruk qayturghan qimmet inawetsiz"
#define LANG_ERR_EXECUTER_RUNNABLE_NOT_FOUND "ijra qilinghuchi tepilmidi"
#define LANG_ERR_EXECUTER_INVALID_DEVIDE "bolguchi san nol bolsa bolmaydu"
#define LANG_ERR_EXECUTER_INVALID_NAME "inawetsiz isim uchritildi"
#define LANG_ERR_EXECUTER_INVALID_KEY "inawetsiz achquch uchritildi"
#define LANG_ERR_EXECUTER_INVALID_VARIABLE "inawetsiz miqdar uchritildi"
#define LANG_ERR_EXECUTER_VARIABLE_ALREADY_DEFINED "miqdar alliburun iniqlanghan"
#define LANG_ERR_EXECUTER_VARIABLE_FAILURE_DEFINED "miqdar muweppiqyetlik iniqlanmini"
#define LANG_ERR_EXECUTER_STACK_OVERFLOW "saqlash boshluqi teship ketti"
